"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const reportCharts = require("../static/report-charts.js");
const reportThreats = require("../static/report-utils.js");

const copy = {
  language: "en", reportWord: "report", reportTypes: { weekly: "Weekly", monthly: "Monthly" },
  generatedBy: "Generated by Cyber Dashboard", none: "None", unknownActor: "Unknown",
  dailySummary: "Daily summary", noSummary: "No summary", day: "2026-09-25",
  labels: { total: "Total", critical: "Critical", high: "High", medium: "Medium",
    actors: "Actors", topThreat: "Top threat", sectors: "Sectors", summary: "Summary", article: "Article", date: "Date" }
};

function exporter() {
  let markup = "";
  const window = {
    open: () => ({ document: { open() {}, write(value) { markup = value; }, close() {} }, addEventListener() {} }),
    setTimeout() {}
  };
  vm.runInNewContext(fs.readFileSync(require.resolve("../static/export.js"), "utf8"), { window, reportCharts, reportThreats });
  return { api: window.cyberDashboardExport, markup: () => markup };
}

test("weekly and monthly PDF preserve the full cover before charts and details", () => {
  for (const type of ["weekly", "monthly"]) {
    const output = exporter();
    output.api.downloadReportPDF({ type, period_start: "2026-09-01", period_end: "2026-09-07",
      summary: "Overview\n■ Detail\n- Complete detail.", charts: {
        attack_methods: [{ label: "Phishing", value: 4 }], threat_actors: [{ label: "APT28", value: 4 }]
      } }, copy);
    const html = output.markup();
    const sections = ['class="document-header"', 'class="report-cover"', 'class="metric-grid"', '>Top threat</h3>', '>Actors</h3>', 'class="section report-summary"', '>Overview</p>', 'class="report-charts"', 'class="report-details"'];
    const positions = sections.map(section => html.indexOf(section));
    assert.ok(positions.every((position, index) => position >= 0 && (index === 0 || position > positions[index - 1])), positions.join(", "));
    assert.equal(html.split('class="report-charts"').length - 1, 1);
    assert.ok(html.includes("Complete detail."));
  }
});

test("daily PDF remains chart-free and retains its summary", () => {
  const output = exporter();
  output.api.downloadDailyPDF({ articles: [], summary: "Daily overview" }, copy);
  assert.ok(output.markup().includes("Daily overview"));
  assert.ok(!output.markup().includes('class="report-charts"'));
});
